//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKeHoach.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GproPlanEntities : DbContext
    {
        public GproPlanEntities()
            : base("name=GproPlanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<P_Customer> P_Customer { get; set; }
        public DbSet<P_ReceptDetail> P_ReceptDetail { get; set; }
        public DbSet<P_Reception> P_Reception { get; set; }
    }
}
