//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKeHoach.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CurrencyUnit
    {
        public P_CurrencyUnit()
        {
            this.P_Reception = new HashSet<P_Reception>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<P_Reception> P_Reception { get; set; }
    }
}
