//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKeHoach.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Reception
    {
        public P_Reception()
        {
            this.P_ReceptDetail = new HashSet<P_ReceptDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CurrencyUnitId { get; set; }
        public int CustomerId { get; set; }
        public double ExchangeRate { get; set; }
        public string Note { get; set; }
        public bool Status { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual P_CurrencyUnit P_CurrencyUnit { get; set; }
        public virtual P_Customer P_Customer { get; set; }
        public virtual ICollection<P_ReceptDetail> P_ReceptDetail { get; set; }
    }
}
